# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: OsuRulesetsTemplate

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  EmptyFreeform:  
    name: EmptyFreeform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: install template
      run: dotnet new -i ppy.osu.Game.Templates
    - name: get Empty Rulesets
      run: dotnet new ruleset -n MyCoolRuleset -o MyProject/Ruleset
    - name: upload projects
      uses:  actions/upload-artifact@v3
      with:
          name: EmptyFreeform
          path: MyProject/Ruleset
    
  EmptyScrolling:
    name: EmptyScrolling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: install template
      run: dotnet new -i ppy.osu.Game.Templates
    - name: get Empty Rulesets
      run: dotnet new ruleset-scrolling -n MyCoolRuleset -o MyProject/Ruleset
    - name: upload projects
      uses:  actions/upload-artifact@v3
      with:
          name: EmptyScrolling
          path: MyProject/Ruleset

  ExampleFreefrom:
    name: ExampleFreefrom
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: install template
      run: dotnet new -i ppy.osu.Game.Templates
    - name: get Empty Rulesets
      run: dotnet new ruleset-example -n MyCoolWorkingRuleset -o MyProject/Ruleset
    - name: upload projects
      uses:  actions/upload-artifact@v3
      with:
          name: ExampleFreeform
          path: MyProject/Ruleset

  ExampleScrolling:
    name: ExampleScrolling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: install template
      run: dotnet new -i ppy.osu.Game.Templates
    - name: get Empty Rulesets
      run: dotnet new ruleset-scrolling-example -n MyCoolWorkingRuleset -o MyProject/Ruleset
    - name: upload projects
      uses:  actions/upload-artifact@v3
      with:
          name: ExampleScrolling
          path: MyProject/Ruleset
